id: PC7518B4E
initial_creation_type: input
source_metadata:
  title: Adeu Rinpoche Series
  language: bo
  description: 'Texts by and about the Eighth Trulshik Adeu Rinpoche, Druprik Khyuchok
    (''khrul zhig a lde''u grub rigs khyu mchog, 1931–2007), a senior Drukpa Kagyü
    master from Nangchen:'
  volume:
    25d1bb416ab948549ce5ee692f06f6a0:
      title: Magnetizing (Wangdü) Prayer
      parent: Prayers
    24feea85dcbb47fb86c5d4889cf0e2b2:
      title: Prayer to Drukpa Kunley
      parent: Prayers
    4a3a72f7740e49e5b88cf7a013f54149:
      title: Windhorse Practice of Tārā
      parent: Prayers
    4f9f1a6ac0794889ba4f91a43475eab0:
      title: 'The Falling Rain of Blessings: A Brief Daily Practice of the Wealth
        Deity White Jambhala'
      parent: Sādhanas
created_at: '2022-02-28T22:34:23.465494'
last_modified_at: '2022-02-28T22:34:23.465497'
